spring.application.name=sistema-escolar

spring.datasource.url=jdbc:mysql://localhost:3306/sistema_escolar?useSSL=false&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Guerreir@126
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
server.port=8080
