server.port=${PORT}

spring.datasource.url=jdbc:mysql://hopper.proxy.rlwy.net:46478/railway
spring.datasource.username=root
spring.datasource.password=tJDJzwVvcnWIjQhFzGMboaStNacNFWfs

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.cache=false